version: "3.4"
services:
  app:
    container_name: workout_tracker
    restart: always
    build:
      context: ..
      target: dev
    ports:
      - 8000:8000
    env_file: ../.env
    command: sleep infinity
    links:
      - postgres
    volumes:
      - ..:/workspace:cached
  postgres:
    container_name: postgres
    image: postgres:12.3
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - ../postgres_db:/var/lib/postgresql/data/
